# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               ProbablePrime
tagline:             'Rambelings and Musings'
description:         ''
url:                 http://probableprime.co.uk
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              ProbablePrime
  url:               https://twitter.com/probableprime
  email:             markdotto@gmail.com

# Custom vars
version:             1.0.0
