# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               ProbablePrime
tagline:             'Rambelings and Musings'
description:         ''
url:                 http://probableprime.co.uk
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              ProbablePrime
  url:               https://twitter.com/probableprime
  email:             prime@ahref.co.uk

gems: [jekyll/tagging]

exclude: [BlogLayout]

# Custom vars
version:             1.0.0

#Tag Plugin vars
tag_page_layout: tag_page
tag_page_dir: tag
tag_feed_layout: tag_feed
tag_feed_dir: tag

#ignored_tags:[]
